//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proaxis
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int itemID { get; set; }
        public string itemDescription { get; set; }
        public decimal itemPrice { get; set; }
        public int itemStock { get; set; }
    }
}
