//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proaxis
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int testID { get; set; }
        public string testName { get; set; }
        public decimal testPrice { get; set; }
    }
}
